export const LOGIN_DURATION = '7d'
export const ROLE_ADMIN = 'admin'
export const LOGIN_PATH = '/login'
export const FILE_DOMAIN = "localhost:3000/api/file";

export const crimeTypes = [
    "Homicide",
    "Manslaughter",
    "Assault",
    "Domestic Violence",
    "Kidnapping",
    "Human Trafficking",
    "Rape",
    "Sexual Assault",
    "Child Abuse",
    "Theft",
    "Burglary",
    "Robbery",
    "Vandalism",
    "Arson",
    "Bribery",
    "Counterfeiting",
    "Insider Trading",
    "Drug Possession",
    "Drug Trafficking",
    "DUI (Driving Under Influence)",
    "Public Intoxication",
    "Illegal Drug Manufacturing",
    "Gang Activity",
    "Illegal Gambling",
    "Smuggling",
    "Extortion",
    "Contract Killing",
    "Terrorism",
    "Corruption",
    "Treason",
    "Rioting",
    "Election Fraud",
    "Obstruction of Justice",
    "Illegal Wildlife Trade",
    "Pollution",
    "Poaching",
    "Deforestation",
    "Illegal Waste Disposal",
    "Indecent Exposure",
    "Prostitution",
    "Hate Speech",
    "Obscene Publications"
]